# Generated by Django 5.0.7 on 2026-03-01 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dueño',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('especie', models.CharField(max_length=50)),
                ('raza', models.CharField(max_length=50)),
                ('edad', models.PositiveIntegerField()),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('vacunado', models.BooleanField(default=False)),
                ('dueño', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascotas', to='pets.dueño')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alergias', models.TextField(blank=True)),
                ('fecha_visita', models.DateField()),
                ('motivo_visita', models.CharField(max_length=200)),
                ('diagnostico', models.TextField()),
                ('tratamiento', models.TextField()),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiales_medicos', to='pets.mascota')),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('motivo', models.TextField(max_length=200)),
                ('veterinario', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Confirmada', 'Confirmada'), ('Cancelada', 'Cancelada')], max_length=50)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='pets.mascota')),
            ],
        ),
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_vacuna', models.CharField(max_length=100)),
                ('fecha_aplicacion', models.DateField()),
                ('veterinario', models.CharField(max_length=100)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.mascota')),
            ],
        ),
    ]
