# Generated by Django 4.2.30 on 2026-05-02 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
        ('inventory', '0002_alter_producto_nombre'),
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CITA', 'Cita'), ('PRODUCTO', 'Producto'), ('OTRO', 'Otro')], max_length=20)),
                ('descripcion', models.CharField(max_length=200)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pets.cita')),
            ],
        ),
        migrations.RemoveField(
            model_name='mascota',
            name='cliente',
        ),
        migrations.DeleteModel(
            name='Servicio',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='cliente_direccion',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='cliente_email',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='cliente_nombre',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='cliente_telefono',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='mascota_edad',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='mascota_especie',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='mascota_nombre',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='mascota_raza',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='servicio_cantidad',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='servicio_descripcion',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='servicio_precio',
        ),
        migrations.AddField(
            model_name='factura',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pets.dueño'),
        ),
        migrations.AddField(
            model_name='factura',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('PENDIENTE', 'Pendiente'), ('PAGADA', 'Pagada'), ('CANCELADA', 'Cancelada')], default='BORRADOR', max_length=20),
        ),
        migrations.AddField(
            model_name='factura',
            name='mascota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pets.mascota'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='factura',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='factura',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Mascota',
        ),
        migrations.AddField(
            model_name='facturadetalle',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='billing.factura'),
        ),
        migrations.AddField(
            model_name='facturadetalle',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.producto'),
        ),
    ]
