# Generated by Django 5.0.7 on 2026-03-01 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_mascota', models.CharField(max_length=100, verbose_name='Nombre de la Mascota')),
                ('dueño_mascota', models.CharField(max_length=100, verbose_name='Dueño de la Mascota')),
                ('dueño_telefono', models.CharField(max_length=20, verbose_name='Teléfono del Dueño')),
                ('dueño_email', models.EmailField(max_length=254, verbose_name='Correo del Dueño')),
                ('tipo', models.CharField(choices=[('Consulta', 'Consulta General'), ('Vacunación', 'Vacunación'), ('Cirugía', 'Cirugía'), ('Peluqueria', 'Peluqueria'), ('Control', 'Control'), ('Emergencia', 'Emergencia')], default='Consulta', max_length=50, verbose_name='Tipo de Cita')),
                ('fecha_cita', models.DateTimeField(verbose_name='Fecha de la Cita')),
                ('hora_cita', models.TimeField(verbose_name='Hora de la Cita')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Confirmada', 'Confirmada'), ('Completada', 'Completada'), ('Cancelada', 'Cancelada')], default='Pendiente', max_length=20, verbose_name='Estado de la Cita')),
                ('sintomas', models.TextField(blank=True, null=True, verbose_name='Síntomas de la Mascota')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas Adicionales')),
            ],
        ),
    ]
