# Generated by Django 4.2.30 on 2026-05-07 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
        ('veterinary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='dueño_email',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='dueño_mascota',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='dueño_telefono',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='nombre_mascota',
        ),
        migrations.AddField(
            model_name='cita',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pets.dueño'),
        ),
        migrations.AddField(
            model_name='cita',
            name='mascota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pets.mascota'),
        ),
    ]
